### ISSUE TITLE
How to get consumer key and secret?

### ISSUE THREAD

**Issue by wnm** [xing/xing_api#14]
Hi there,

I signed up on dev.xing.com, but when I go to https://dev.xing.com/applications (as described in the docs) I only see:

"You don’t have any apps, ask your XING representative if you need to create one."

There is no link to create an app, and no contact info. Who is my XING representative? How can I create an application?

wnm

**Comment by johanness** [comment]
Hi wnm!

I'm sorry to say, but the XING public API has been closed. The anouncement can be found in the [xing developer group](https://www.xing.com/communities/posts/important-information-about-xing-public-api-support-1012409468)

Quote:
> Dear XING public API consumer,
> In 2012 we introduced our public API to enable people to develop applications that make use of specific XING data.
> Today we’d like to inform you that we’ve decided to take a new direction, meaning that in the future we intend to focus on a collaboration with a few selected business partners.
> At the turn of the year we’ll cease supporting the XING public API and have already disabled the option to register new applications. Currently registered applications can of course continue to use existing public API calls. Please make any necessary changes to your registered applications, e.g. descriptions for the oAuth dialogue or callback URLs, by the 31st of January 2017.
> As mentioned above, the registration process has already been removed from the developer portal https://dev.xing.com/. This developer group will no longer be operated in 2017.
> The XING API team would like to thank you for the great collaboration over the last few years. You’ve shown us that a public API bears a number of opportunities, and we really enjoyed working with you!

**Comment by Paratron** [comment]
Is it such a problem to change that message to "The XING public API has been discontinued and you cannot create applications anymore"?

This would have been a million times more informative and accurate.

**Comment by jalerson** [comment]
@Paratron totally agree!!!

**Comment by OzanKurt** [comment]
Good job Xing total nonsense...
