### ISSUE TITLE
Access response headers

### ISSUE THREAD

**Issue by tak1n** [xing/xing_api#15]
Hello there! First of thx for this awesome gem :)

We are currently facing a problem because of https://github.com/xing/xing_api/blob/master/lib/xing_api/response_handler.rb#L23 where the `response.body` get's parsed and is returned.

The problem is that eg for [Comment#create](https://dev.xing.com/docs/post/activities/:activity_id/comments) the uid of the comment is part of the location header. Furthermore I currently see no way how to access the whole response object or headers of it.

Did I miss something or is there really no way?

Cheers
Benny

**Comment by johanness** [comment]
Hi Benny!

What do you think if the `handle` returns a hash that has a `headers` method returning the header data?
Or what would you expect?

Greetings Johannes

**Comment by tak1n** [comment]
Hey Johannes!

A headers method would be nice, but even just returning the Net::HTTPResponse would be fine for me.
The latter would mean a gem user could easily look up the stdlib doc of Net::HTTP and see how to access those things :)

I leave that up to you to decide, but probably the header method on a hash like object would be good in terms of backwards compat (it already returned a hash).
Just inform me I can craft together a pull request

Cheers
Benny

**Comment by johanness** [comment]
Yes I would prefer a header method for the compatibility. A pull request would be awesome!

**Comment by tak1n** [comment]
@johanness sorry we need to reopen it and craft another PR.

The problem is that `XingApi::Activity::Comment.create` works likes expected and returns a `XingApi::Response`, but `XingApi::Company::Update::Comment.create` still returns a `Hash`.

Need to dig into the code to see why that is like that :)

**Comment by tak1n** [comment]
Whoops missed that line: https://github.com/xing/xing_api/blob/master/lib/xing_api/response_handler.rb#L17

**Comment by tak1n** [comment]
@johanness another problem is that https://dev.xing.com/docs/post/companies/updates/:id/comments does not return a location header for successful creations, but that's out of the scope for a gem being a wrapper around  the api :smile:
