### ISSUE TITLE
How can I create app on Xing? Mainly for Login with Xing

### ISSUE THREAD

**Issue by bhargavtristate** [xing/xing_api#18]
Hello, I can not create App and I am getting following message.

You don’t have any apps, ask your XING representative if you need to create one.

But I did not get any link or source from where, can you please help me?

I can get button from Login with Xing, but it is not being placed on html page where I want to set.

I really need help, please give me source of contact.

**Comment by johanness** [comment]
Hi!

I fear the support from XING directly has been stopped. Try to go with the [documentation for the Login with XING plugin](https://dev.xing.com/plugins/login_with/docs#get-started). You will have to login there with your XING account to access the information.
