### ISSUE TITLE
Get more information on errors

### ISSUE THREAD

**Issue by larryh** [xing/xing_api#8]
Hi,

First: thanks for creating this gem!

And now for my question...

I have been able to authenticate a user and post to his account. However, many times I get the following error:

XingApi::InvalidParameterError: 403 - INVALID_PARAMETERS - Invalid parameters> : 403 - INVALID_PARAMETERS - Invalid parameters 
text is Invalid parameters

The documentation on Error Handling shows the offending fields, however the output I am getting back does not. (The 'text' output is the field described in your documentation. As you can see it provides no additional information.)

Is there any way to get more information on the invalid parameters?

Thanks,
Larry

**Comment by johanness** [comment]
Hi Larry!

There is currently no way to access the `errors` - list on the invalid parameters response. Since it is a documented behaviour of the API, it should be possible to access the errors list.

I will make a feature branch with a suggestions for a solution.

Thanks

**Comment by larryh** [comment]
Hi Johanness,

Thanks for the reply. I've been able to work around this, so please don't go to any extra work for me.

Thanks again,
Larry

**Comment by johanness** [comment]
Hey Larry,

If you have a solution that worked for you, maybe you could open a pull request.

Greetings

**Comment by larryh** [comment]
The "work around" was just accepting the fact that we couldn't get any more information and moving on. Sorry, I should have been more precise with my terminology.

Thanks,
Larry
